# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b46a0a610036991ac5ab6b454bce04db447fcd13b32a046e1d577bae1a956649a4f97452fda393a10d84d257540ee051a81f4881a7eb1b6a6e6b0d8839f45efe

test:
  secret_key_base: f0d4407f1c587e5a6986005056617ec248fad31024dbc39fe3e47536f3a8fd7f076c7cd71b514fea5c74c515bfed77ed18aaf10440261569e4477a5bbd38f0a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
